# Generated by Django 5.2 on 2025-05-19 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('prepared_time', models.IntegerField(default=True)),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
