# Generated by Django 5.2 on 2025-05-19 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='prepared_time',
            field=models.IntegerField(default=datetime.time),
        ),
    ]
