# Generated by Django 5.2.1 on 2025-05-22 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_alter_food_prepared_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='prepared_time',
            field=models.TimeField(default=datetime.time),
        ),
    ]
