# Generated by Django 5.2.1 on 2025-06-04 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_alter_food_prepared_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='cooldrinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('prepared_time', models.TimeField(default=datetime.time)),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='starters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('prepared_time', models.TimeField(default=datetime.time)),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('prepared_time', models.TimeField(default=datetime.time)),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
