# Generated by Django 5.2.1 on 2025-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagesb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
