# Generated by Django 5.2.1 on 2025-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_imagesb'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title1', models.CharField(max_length=300)),
            ],
        ),
    ]
