# Generated by Django 5.2.1 on 2025-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title2',
            field=models.CharField(default='second title', max_length=300),
        ),
    ]
