# Generated by Django 5.2.1 on 2025-08-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_homepage_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooldrinks',
            name='category',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='starters',
            name='category',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='veg',
            name='category',
            field=models.CharField(max_length=60),
        ),
    ]
